apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    {%- for label_key, label_value in ksm_labels.items() %}
    {{ label_key ~ ":" ~ " " ~ label_value | safe }}
    {%- endfor %}
  name: {{ ksm_service_account_metadata_name | default("kube-state-metrics-sa") }}
  namespace: {{ namespace | default("kube-system") }}
---
{%- for cluster_role in ksm_cluster_role_file_path %}
{% include cluster_role %}
---
{%- endfor %}
{%- for cluster_role in cluster_roles %}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {%- for label_key, label_value in ksm_labels.items() %}
    {{ label_key ~ ":" ~ " " ~ label_value | safe }}
    {%- endfor %}
  name: {{ cluster_role.ksm_cluster_role_binding_metadata_name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ cluster_role.ksm_cluster_role_metadata_name }}
subjects:
- kind: ServiceAccount
  name: {{ cluster_role.ksm_service_account_metadata_name }}
  namespace: {{ namespace | default("kube-system") }}
---
{%- endfor %}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {%- for label_key, label_value in ksm_labels.items() %}
    {{ label_key ~ ":" ~ " " ~ label_value | safe }}
    {%- endfor %}
  name: {{ ksm_deployment_metadata_name | default("kube-state-metrics-d") }}
  namespace: {{ namespace | default("kube-system") }}
spec:
  replicas: {{ ksm_deployment_replicas | default("1") }}
  selector:
    matchLabels:
      {%- for label_key, label_value in ksm_labels.items() %}
      {{ label_key ~ ":" ~ " " ~ label_value | safe }}
      {%- endfor %}
  template:
    metadata:
      labels:
        {%- for label_key, label_value in ksm_labels.items() %}
        {{ label_key ~ ":" ~ " " ~ label_value | safe }}
        {%- endfor %}
    spec:
      automountServiceAccountToken: true
      containers:
      - image: {{ ksm_deployment_container_image | default("registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.2") }}
        livenessProbe:
          httpGet:
            path: {{ ksm_livenessProbe_path | default("/healthz")}}
            port: {{ kube_state_metrics_livenessProbe_port | default("8080")}}
          initialDelaySeconds: {{ ksm_livenessProbe_initialDelaySeconds | default("5") }}
          timeoutSeconds: {{ ksm_livenessProbe_timeoutSeconds | default("5") }}
        name: {{ ksm_deployment_container_name | default("kube-state-metrics-deployment") }}
        ports:
        - containerPort: {{ ksm_containerPort | default("8080") }}
          name: {{ ksm_containerPort_name | default("http-metrics") }}
        - containerPort: {{ ksm_telemetry_containerPort | default("8081") }}
          name: {{ ksm_telemetry_containerPort_name | default("telemetry") }}
        readinessProbe:
          httpGet:
            path: {{ ksm_readinessProbe_path | default("/") }}
            port: {{ ksm_readinessProbe_port | default("8081") }}
          initialDelaySeconds: {{ ksm_readinessProbe_initialDelaySeconds | default("5") }}
          timeoutSeconds: {{ ksm_readinessProbe_timeoutSeconds | default("5") }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          seccompProfile:
            type: RuntimeDefault
      nodeSelector:
        {{ ksm_deployment_nodeSelector | default("kubernetes.io/os" ~ ":" ~ " " ~ "linux") }}
      serviceAccountName: {{ ksm_service_account_metadata_name | default("kube-state-metrics-sa") }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {%- for label_key, label_value in ksm_labels.items() %}
    {{ label_key ~ ":" ~ " " ~ label_value | safe }}
    {%- endfor %}
  name: {{ ksm_service_metadata_name | default("kube-state-metrics") }}
  namespace: {{ namespace | default("kube-system") }}
spec:
  clusterIP: None
  ports:
  - name: {{ ksm_containerPort_name | default("http-metrics") }}
    port: {{ ksm_containerPort | default("8080") }}
    targetPort: {{ ksm_containerPort_name | default("http-metrics") }}
  - name: {{ ksm_telemetry_containerPort_name | default("telemetry") }}
    port: {{ ksm_telemetry_containerPort | default("8081") }}
    targetPort: {{ ksm_telemetry_containerPort_name | default("telemetry") }}
  selector:
    {%- for label_key, label_value in ksm_labels.items() %}
    {{ label_key ~ ":" ~ " " ~ label_value | safe }}
    {%- endfor %}
