apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-efs-csi-driver
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-efs-csi-driver-deployer
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["policy"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch", "extensions", "scheduling.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-efs-csi-driver-deployer-binding
subjects:
- kind: ServiceAccount
  name: aws-efs-csi-driver
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: aws-efs-csi-driver-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-cluster-admin
subjects:
- kind: ServiceAccount
  name: aws-efs-csi-driver
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-aws-efs-csi-driver
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: aws-efs-csi-driver
    spec:
      serviceAccountName: aws-efs-csi-driver
      containers:
      - name: kubectl
        image: bitnami/kubectl
        command: ["kubectl"]
        args: ["apply", "-k", "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.5"]
      restartPolicy: Never