kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ am_configmap_metadata_name | default("alertmanager-config") }}
  namespace: {{ namespace }}
data:
  {{ am_conf_file_path.split('/')[-1] }}: |-
    {%- macro render_with_indent() %}{% include am_conf_file_path %}{% endmacro %}
    {{ render_with_indent()|indent }}
---
{%- if volumes %}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ am_efs_sc_metadata_name | default("am-efs-sc") }}
  namespace: {{ namespace }}
provisioner: {{ am_efs_sc_provisioner | default("efs.csi.aws.com") }}
parameters:
  provisioningMode: {{ am_efs_sc_provisioningMode | default("efs-ap") }}
  fileSystemId: {{ am_efs_sc_fileSystemId }}
  directoryPerms: {{ am_efs_sc_directoryPerms | default("'755'") | safe }}
  basePath: {{ am_efs_sc_basePath | default("'/alert_manager_dynamic_provisioning'") | safe }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ am_efs_pvc_metadata_name | default("am-efs-pvc") }}
  namespace: {{ namespace }}
spec:
  accessModes:
{%- for am_efs_pvc_accessMode in am_efs_pvc_accessModes %}
    - {{ am_efs_pvc_accessMode }}
{%- endfor %}
  storageClassName: {{ am_efs_sc_metadata_name | default("am-efs-sc") }}
  resources:
    requests:
      storage: {{ am_efs_pvc_resources_storage | default("5Gi") }}
---
{%- endif %}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{am_deployment_metadata_name | default("am-deployment")}}
  namespace: {{ namespace }}
spec:
  replicas: {{ am_deployment_replicas | default("1")}}
  selector:
    matchLabels:
      {%- for label_key, label_value in am_labels.items() %}
      {{ label_key ~ ":" ~ " " ~ label_value | safe }}
      {%- endfor %}
  template:
    metadata:
      name: {{ am_template_metadata_name | default("am-template") }}
      labels:
        {%- for label_key, label_value in am_labels.items() %}
        {{ label_key ~ ":" ~ " " ~ label_value | safe }}
        {%- endfor %}
    spec:
      containers:
      - name: {{ am_container_name | default("am-container") }}
        image: {{ am_deployment_image | default("prom/alertmanager:latest") }}
        args:
          - "--config.file=/etc/alertmanager/{{ am_conf_file_path.split('/')[-1] }}"
          - "--storage.path={{am_persistent_data_storage_path | default("/alertmanager")}}"
        ports:
        - name: am-port
          containerPort: {{ am_deployment_container_port | default("9093") }}
        resources:
            requests:
              cpu: {{ am_cpu_requests | default("500m")}}
              memory: {{ am_memory_requests | default("500M") }}
            limits:
              cpu: {{ am_cpu_limits | default("1") }}
              memory: {{ am_memory_limits | default("1Gi") }}
        volumeMounts:
        - name: {{ am_config_volume | default("config-volume") }}
          mountPath: {{ am_config_volume_mountPath | default("/etc/alertmanager")}}
        {%- if volumes %}
        - name: {{ am_persistent_data_volume | default("am-persistent-volume") }}
          mountPath: {{am_persistent_data_storage_path | default("/alertmanager")}}
        {%- endif %}
      volumes:
      - name: {{ am_config_volume | default("config-volume") }}
        configMap:
          name: {{ am_configmap_metadata_name | default("alertmanager-config") }}
      {%- if volumes %}
      - name: {{ am_persistent_data_volume | default("am-persistent-volume") }}
        persistentVolumeClaim:
          claimName: {{ am_efs_pvc_metadata_name | default("am-efs-pvc") }}
      {%- endif %}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ am_service_metadata_name | default("alertmanager") }}
  namespace: {{ namespace }}
  annotations:
      {{ am_prometheus_scrape | default("prometheus.io/scrape: 'true'") | safe }}
      {{ am_prometheus_port | default("prometheus.io/port:   '9093'") | safe }}
spec:
  selector: 
    {%- for label_key, label_value in am_labels.items() %}
    {{ label_key ~ ":" ~ " " ~ label_value | safe }}
    {%- endfor %}
  ports:
    - port: {{ am_service_port | default("9093") }}
      targetPort: {{ am_deployment_container_port | default("9093") }}
  type: {{ am_service_type | default("ClusterIP") }}